stages:
  - build
  - deploy


build-docker:
  stage: build
  image:
    name: woozymasta/kaniko-tools
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/deployment/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/deployment"
  only:
    - main
    - master

deploy-staging:
  stage: deploy
  image: tiangolo/docker-with-compose
  needs: 
    - build-docker
  tags: 
    - docker-swarm-depl  
  script:
    - printf "\nSTG_VERSION=${VERSION}" >> ./deployment/docker/.env
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    # - docker stack deploy -c deployment/docker-compose.yml --with-registry-auth my-stack
    - docker-compose --env-file ./deployment/.env -f deployment/docker-compose.yml pull
    - docker-compose --env-file ./deployment/.env -f deployment/docker-compose.yml up -d 
  only:
    - main
    - master